import { expect } from "chai";
import hre from "hardhat";
import { loadFixture } from "@nomicfoundation/hardhat-network-helpers";
// Type will be generated by hardhat during test execution
// import { VideoDemo } from "../types";

/**
 * @title VideoDemo Tests
 * @notice Comprehensive tests for VideoDemo contract
 * @chapter basic
 */
describe("VideoDemo", function () {
  /**
   * @notice Deploy contract fixture
   * @dev Reusable deployment function for tests
   */
  async function deployContractFixture() {
    const [owner, user1, user2] = await hre.ethers.getSigners();
    
    const ContractFactory = await hre.ethers.getContractFactory("VideoDemo");
    const contract = await ContractFactory.deploy();
    await contract.waitForDeployment();
    
    // Get contract address
    const contractAddress = await contract.getAddress();
    
    // Assert coprocessor is initialized (this sets up the FHEVM environment)
    await hre.fhevm.assertCoprocessorInitialized(contract, "VideoDemo");
    
    return { contract, owner, user1, user2, contractAddress };
  }

  describe("Deployment", function () {
    it("Should deploy successfully", async function () {
      const { contract } = await loadFixture(deployContractFixture);
      expect(await contract.getAddress()).to.be.properAddress;
    });
  });

  // TODO: Add your test cases here
  describe("Functionality", function () {
    it("Should work correctly", async function () {
      const { contract, contractAddress, owner } = await loadFixture(deployContractFixture);
      // TODO: Add test implementation
      // Example: Create encrypted input using hre.fhevm
      // const input = hre.fhevm.createEncryptedInput(contractAddress, owner.address);
      // input.add64(42);
      // const encryptedInput = await input.encrypt();
    });
  });
});
